name: TEST_SLOT

on:
  #schedule:
  #  - cron:  '*/30 05-22 * * *'
  workflow_dispatch:

env:
    TELEGRAM: ${{ secrets.TELEGRAM }}
    CHAT_ID: ${{ secrets.CHAT_ID }}

jobs:
  UPDATE-ALL:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: First try
        if: always()
        run:  ./doctobot.ps1
        
      - name: Retry if failed
        if: failure()
        run:  ./doctobot.ps1
